spring.application.name=Car-Rental
server.port=9070

spring.datasource.url=jdbc:mysql://localhost:3306/carRental2
spring.datasource.username=root
spring.datasource.password=Madhan@2006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


server.error.whitelabel.enabled=false